[package]
name = "lua-json5"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pest = "2.8"
pest_derive = "2.8"
mlua = { version = "0.10", features = ["luajit", "module", "macros"] }
